export enum INTERSEPTOR_KEYS {
  WITHOUT_JWT = 'WITHOUT_JWT',
  WITHOUT_DEFAULT_API = 'WITHOUT_DEFAULT_API',
  WITHOUT_REFRESH_TOKEN = 'WITHOUT_REFRESH_TOKEN',
  WITHOUT_HTTP_ERROR = 'WITHOUT_HTTP_ERROR',
}
